#This Travis config template file was taken from https://github.com/FriendsOfCake/travis
sudo: true
dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@0.0.0.0/cakephp_test'
  global:
    - DEFAULT=1

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.2
    - php: nightly

install:
  - composer validate --strict
  - composer install --no-interaction --no-progress --no-suggest
  - mkdir -p build/logs

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS cakephp_test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'; fi"

script:
  - if [ $TRAVIS_PHP_VERSION != "7.1" ]; then vendor/bin/phpunit --no-coverage; else vendor/bin/phpunit; fi
  - vendor/bin/phpcs

after_success:
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - chmod +x /tmp/codecov.sh
  - /tmp/codecov.sh -s build/logs

notifications:
  email:
    - webdev@qobocloud.com
